### ISSUE TITLE
In addition to images, videos, and open URLs,  other extended types of files will crash app

### ISSUE THREAD

**Issue by zhangsong9008** [KasemJaffer/receive_sharing_intent#149]
In addition to images, videos, and open URLs,  other extended types of files will crash app. where I browser  pdf，docx，text，xls  files ,app crashed.  But  images,videos,open urls sharing work ok. Does anyone have the same problem? 

receive_sharing_intent version 1.4.3

I/flutter (15078): -didChangeAppLifecycleState-0-1616034078674-AppLifecycleState.paused
I/FileDirectory(15078): File name: null
D/AndroidRuntime(15078): Shutting down VM
E/AndroidRuntime(15078): FATAL EXCEPTION: main
E/AndroidRuntime(15078): Process: com.app.block_app, PID: 15078
E/AndroidRuntime(15078): java.lang.NullPointerException
E/AndroidRuntime(15078): 	at java.io.File.<init>(File.java:380)
E/AndroidRuntime(15078): 	at com.kasem.receive_sharing_intent.FileDirectory.getDataColumn(FileDirectory.kt:108)
E/AndroidRuntime(15078): 	at com.kasem.receive_sharing_intent.FileDirectory.getAbsolutePath(FileDirectory.kt:78)
E/AndroidRuntime(15078): 	at com.kasem.receive_sharing_intent.ReceiveSharingIntentPlugin.getMediaUris(ReceiveSharingIntentPlugin.kt:146)
E/AndroidRuntime(15078): 	at com.kasem.receive_sharing_intent.ReceiveSharingIntentPlugin.handleIntent(ReceiveSharingIntentPlugin.kt:119)
E/AndroidRuntime(15078): 	at com.kasem.receive_sharing_intent.ReceiveSharingIntentPlugin.onNewIntent(ReceiveSharingIntentPlugin.kt:236)
E/AndroidRuntime(15078): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry$FlutterEngineActivityPluginBinding.onNewIntent(FlutterEnginePluginRegistry.java:715)
E/AndroidRuntime(15078): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry.onNewIntent(FlutterEnginePluginRegistry.java:391)
E/AndroidRuntime(15078): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onNewIntent(FlutterActivityAndFragmentDelegate.java:599)
E/AndroidRuntime(15078): 	at io.flutter.embedding.android.FlutterFragment.onNewIntent(FlutterFragment.java:678)
E/AndroidRuntime(15078): 	at io.flutter.embedding.android.FlutterFragmentActivity.onNewIntent(FlutterFragmentActivity.java:478)
E/AndroidRuntime(15078): 	at android.app.Activity.performNewIntent(Activity.java:7274)
E/AndroidRuntime(15078): 	at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1370)
E/AndroidRuntime(15078): 	at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1382)
E/AndroidRuntime(15078): 	at android.app.ActivityThread.deliverNewIntents(ActivityThread.java:3372)
E/AndroidRuntime(15078): 	at android.app.ActivityThread.performNewIntents(ActivityThread.java:3393)
E/AndroidRuntime(15078): 	at android.app.ActivityThread.handleNewIntent(ActivityThread.java:3410)
E/AndroidRuntime(15078): 	at android.app.servertransaction.NewIntentItem.execute(NewIntentItem.java:49)
E/AndroidRuntime(15078): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
E/AndroidRuntime(15078): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
E/AndroidRuntime(15078): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2025)
E/AndroidRuntime(15078): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(15078): 	at android.os.Looper.loop(Looper.java:224)
E/AndroidRuntime(15078): 	at android.app.ActivityThread.main(ActivityThread.java:7142)
E/AndroidRuntime(15078): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(15078): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:511)
E/AndroidRuntime(15078): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)
Lost connection to device.

**Comment by petodavid** [comment]
Hi, did you find a solution?

**Comment by zhangsong9008** [comment]
> Hi, did you find a solution?

not yet
