### ISSUE TITLE
App Crashing on Video Share On Android

### ISSUE THREAD

**Issue by RalphMarvin** [KasemJaffer/receive_sharing_intent#150]
Anytime I try to share a video to the app on android. The app just crashes. and prints out the follow:

```
Fatal Exception: java.lang.IllegalArgumentException: Invalid column latitude
       at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:170)
       at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:140)
       at android.content.ContentProviderProxy.query(ContentProviderNative.java:423)
       at android.content.ContentResolver.query(ContentResolver.java:944)
       at android.content.ContentResolver.query(ContentResolver.java:880)
       at android.content.ContentResolver.query(ContentResolver.java:836)
       at com.kasem.receive_sharing_intent.FileDirectory.getDataColumn(FileDirectory.kt:103)
       at com.kasem.receive_sharing_intent.FileDirectory.getAbsolutePath(FileDirectory.kt:78)
       at com.kasem.receive_sharing_intent.ReceiveSharingIntentPlugin.getMediaUris(ReceiveSharingIntentPlugin.kt:146)
       at com.kasem.receive_sharing_intent.ReceiveSharingIntentPlugin.handleIntent(ReceiveSharingIntentPlugin.kt:119)
       at com.kasem.receive_sharing_intent.ReceiveSharingIntentPlugin.onNewIntent(ReceiveSharingIntentPlugin.kt:236)
       at io.flutter.embedding.engine.FlutterEnginePluginRegistry$FlutterEngineActivityPluginBinding.onNewIntent(FlutterEnginePluginRegistry.java:715)
       at io.flutter.embedding.engine.FlutterEnginePluginRegistry.onNewIntent(FlutterEnginePluginRegistry.java:391)
       at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onNewIntent(FlutterActivityAndFragmentDelegate.java:599)
       at io.flutter.embedding.android.FlutterActivity.onNewIntent(FlutterActivity.java:590)
       at android.app.Activity.performNewIntent(Activity.java:7816)
       at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1399)
       at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1412)
       at android.app.ActivityThread.deliverNewIntents(ActivityThread.java:3472)
       at android.app.ActivityThread.handleNewIntent(ActivityThread.java:3484)
       at android.app.servertransaction.NewIntentItem.execute(NewIntentItem.java:53)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7356)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

**Comment by YashSavsani** [comment]
`E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.receive_intent, PID: 13048
    java.lang.IllegalArgumentException: Invalid column latitude
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:170)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:140)
        at android.content.ContentProviderProxy.query(ContentProviderNative.java:423)
        at android.content.ContentResolver.query(ContentResolver.java:944)
        at android.content.ContentResolver.query(ContentResolver.java:880)
        at android.content.ContentResolver.query(ContentResolver.java:836)
        at com.techind.flutter_sharing_intent.MyFileDirectory.getDataColumn(MyFileDirectory.kt:105)
        at com.techind.flutter_sharing_intent.MyFileDirectory.getAbsolutePath(MyFileDirectory.kt:80)
        at com.techind.flutter_sharing_intent.FlutterSharingIntentPlugin.getSharingUris(FlutterSharingIntentPlugin.kt:132)
        at com.techind.flutter_sharing_intent.FlutterSharingIntentPlugin.handleIntent(FlutterSharingIntentPlugin.kt:96)
        at com.techind.flutter_sharing_intent.FlutterSharingIntentPlugin.onNewIntent(FlutterSharingIntentPlugin.kt:246)
        at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onNewIntent(FlutterEngineConnectionRegistry.java:832)
        at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onNewIntent(FlutterEngineConnectionRegistry.java:448)
        at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onNewIntent(FlutterActivityAndFragmentDelegate.java:781)
        at io.flutter.embedding.android.FlutterActivity.onNewIntent(FlutterActivity.java:780)
        at android.app.Activity.performNewIntent(Activity.java:7816)
        at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1399)
        at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1412)
        at android.app.ActivityThread.deliverNewIntents(ActivityThread.java:3472)
        at android.app.ActivityThread.handleNewIntent(ActivityThread.java:3484)
        at android.app.servertransaction.NewIntentItem.execute(NewIntentItem.java:53)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)`
