### ISSUE TITLE
Android app crash when share file from "Downloads" folder

### ISSUE THREAD

**Issue by Dead96** [KasemJaffer/receive_sharing_intent#56]
Same as title, in the emulator when you try to share something in the "Downloads" folder, the app crash.
If you move the file in another folder (eg. /storage/emulated/0/), sharing work perfecty

Edit: If you use a physical device, the app crash when you share a file in the "Recents" page of file explorer.
If you pick the file from the folder where it is located, sharing work perfecty.

For both device, i'm using the android file explorer (com.android.documentsui)

### Stack Trace (Emulator - Downloads folder):

> E/AndroidRuntime(12915): Caused by: java.lang.NumberFormatException: For input string: "raw:/storage/emulated/0/Download/test_file.pdf"
E/AndroidRuntime(12915): 	at java.lang.Long.parseLong(Long.java:590)
E/AndroidRuntime(12915): 	at java.lang.Long.valueOf(Long.java:804)
E/AndroidRuntime(12915): 	at com.kasem.receive_sharing_intent.FileDirectory.getAbsolutePath(FileDirectory.kt:51)
E/AndroidRuntime(12915): 	at com.kasem.receive_sharing_intent.ReceiveSharingIntentPlugin.getMediaUris(ReceiveSharingIntentPlugin.kt:139)
E/AndroidRuntime(12915): 	at com.kasem.receive_sharing_intent.ReceiveSharingIntentPlugin.handleIntent(ReceiveSharingIntentPlugin.kt:112)
E/AndroidRuntime(12915): 	at com.kasem.receive_sharing_intent.ReceiveSharingIntentPlugin.<init>(ReceiveSharingIntentPlugin.kt:41)
E/AndroidRuntime(12915): 	at com.kasem.receive_sharing_intent.ReceiveSharingIntentPlugin$Companion.registerWith(ReceiveSharingIntentPlugin.kt:75)
E/AndroidRuntime(12915): 	at com.kasem.receive_sharing_intent.ReceiveSharingIntentPlugin.registerWith(Unknown Source:2)

### Stack Trace (Device - Recents page):
>E/AndroidRuntime( 9509): Caused by: java.lang.NumberFormatException: For input string: "msf:25"
E/AndroidRuntime( 9509): 	at java.lang.Long.parseLong(Long.java:594)
E/AndroidRuntime( 9509): 	at java.lang.Long.valueOf(Long.java:808)
E/AndroidRuntime( 9509): 	at com.kasem.receive_sharing_intent.FileDirectory.getAbsolutePath(FileDirectory.kt:51)
E/AndroidRuntime( 9509): 	at com.kasem.receive_sharing_intent.ReceiveSharingIntentPlugin.getMediaUris(ReceiveSharingIntentPlugin.kt:139)
E/AndroidRuntime( 9509): 	at com.kasem.receive_sharing_intent.ReceiveSharingIntentPlugin.handleIntent(ReceiveSharingIntentPlugin.kt:112)
E/AndroidRuntime( 9509): 	at com.kasem.receive_sharing_intent.ReceiveSharingIntentPlugin.<init>(ReceiveSharingIntentPlugin.kt:41)
E/AndroidRuntime( 9509): 	at com.kasem.receive_sharing_intent.ReceiveSharingIntentPlugin$Companion.registerWith(ReceiveSharingIntentPlugin.kt:75)
E/AndroidRuntime( 9509): 	at com.kasem.receive_sharing_intent.ReceiveSharingIntentPlugin.registerWith(Unknown Source:2)

### Flutter doctor:

> [√] Flutter (Channel stable, v1.17.1, on Microsoft Windows [Version 10.0.18363.778], locale en-GB)
    • Flutter version 1.17.1 at C:\flutter
    • Framework revision f7a6a7906b (3 days ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2
>
> [√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\\Users\\andre\\AppData\\Local\\Android\\sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.
>
> [√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
>
> [√] VS Code (version 1.45.1)
    • VS Code at C:\Users\andre\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.10.1
>
> [√] Connected device (1 available)
    • Mi 5 • 721d00d0 • android-arm64 • Android 10 (API 29)
>
> • No issues found!

**Comment by rmazumde** [comment]
I am getting same issue with Pixel 2 device.
D/AndroidRuntime( 7307): Shutting down VM
E/AndroidRuntime( 7307): FATAL EXCEPTION: main
E/AndroidRuntime( 7307): Process: com.digital14.katimfiletransfer.katim_file_transfer_client, PID: 7307
E/AndroidRuntime( 7307): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.digital14.katimfiletransfer.katim_file_transfer_client/com.digital14.katimfiletransfer.katim_file_transfer_client.MainActivity}: java.lang.NumberFormatException: For input string: "msf:27"
E/AndroidRuntime( 7307): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
E/AndroidRuntime( 7307): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
E/AndroidRuntime( 7307): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
E/AndroidRuntime( 7307): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime( 7307): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime( 7307): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
E/AndroidRuntime( 7307): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime( 7307): 	at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime( 7307): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/AndroidRuntime( 7307): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 7307): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/AndroidRuntime( 7307): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
E/AndroidRuntime( 7307): Caused by: java.lang.NumberFormatException: For input string: "msf:27"
E/AndroidRuntime( 7307): 	at java.lang.Long.parseLong(Long.java:594)
E/AndroidRuntime( 7307): 	at java.lang.Long.valueOf(Long.java:808)
E/AndroidRuntime( 7307): 	at com.kasem.receive_sharing_intent.FileDirectory.getAbsolutePath(FileDirectory.kt:51)
E/AndroidRuntime( 7307): 	at com.kasem.receive_sharing_intent.ReceiveSharingIntentPlugin.getMediaUris(ReceiveSharingIntentPlugin.kt:139)
E/AndroidRuntime( 7307): 	at com.kasem.receive_sharing_intent.ReceiveSharingIntentPlugin.handleIntent(ReceiveSharingIntentPlugin.kt:112)
E/AndroidRuntime( 7307): 	at com.kasem.receive_sharing_intent.ReceiveSharingIntentPlugin.<init>(ReceiveSharingIntentPlugin.kt:41)
E/AndroidRuntime( 7307): 	at com.kasem.receive_sharing_intent.ReceiveSharingIntentPlugin$Companion.registerWith(ReceiveSharingIntentPlugin.kt:75)
E/AndroidRuntime( 7307): 	at com.kasem.receive_sharing_intent.ReceiveSharingIntentPlugin.registerWith(Unknown Source:2)
E/AndroidRuntime( 7307): 	at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:34)
E/AndroidRuntime( 7307): 	at com.digital14.katimfiletransfer.katim_file_transfer_client.MainActivity.configureFlutterEngine(MainActivity.kt:13)
E/AndroidRuntime( 7307): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:178)
E/AndroidRuntime( 7307): 	at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:409)
E/AndroidRuntime( 7307): 	at android.app.Activity.performCreate(Activity.java:7802)
E/AndroidRuntime( 7307): 	at android.app.Activity.performCreate(Activity.java:7791)
E/AndroidRuntime( 7307): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299)
E/AndroidRuntime( 7307): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
E/AndroidRuntime( 7307): 	... 11 more
I/Process ( 7307): Sending signal. PID: 7307 SIG: 9

**Comment by Aderos** [comment]
I fixed this problem https://github.com/Aderos/receive_sharing_intent/tree/stable

**Comment by yzhong52** [comment]
What's the actual fix? Is it these two lines: 

```
    <uses-permission android:name="android.permission.ACCESS_DOWNLOAD_MANAGER" />
    <uses-permission android:name="android.permission.ACCESS_ALL_DOWNLOADS" />
```

@Aderos ?

**Comment by marcqtan** [comment]
see my fix here: https://github.com/marcqtan/receive_sharing_intent/commit/ff6fa402a687d14ce45f0babfc4a5b76f84de976
