### ISSUE TITLE
Getting error while running IOS build

### ISSUE THREAD

**Issue by maskaravivek** [KasemJaffer/receive_sharing_intent#6]
I get the following error while running the Xcode build. How can I fix this? 
```
Running Xcode build...
[{"event":"app.progress","params":{"appId":"6aeb6283-2fd1-40ed-b62e-75580b9689dd","id":"1","progressId":null,"message":"Running Xcode build..."}}]
[+1851 ms] executing: [/Users/vivekmaskara/Documents/Projects/commons/ios/] /usr/bin/env xcrun xcodebuild -configuration Debug -quiet -workspace Runner.xcworkspace -scheme Runner BUILD_DIR=/Users/vivekmaskara/Documents/Projects/commons/build/ios -sdk iphonesimulator -arch x86_64
[+3504 ms] === BUILD TARGET sqflite OF PROJECT Pods WITH CONFIGURATION Debug ===
           ld: framework not found receive_sharing_intent
           clang: error: linker command failed with exit code 1 (use -v to see invocation)

           ** BUILD FAILED **
[{"event":"app.progress","params":{"appId":"6aeb6283-2fd1-40ed-b62e-75580b9689dd","id":"1","progressId":null,"finished":true}}]
[  +11 ms] Xcode build done.                                            3.5s

```

**Comment by maskaravivek** [comment]
Attaching more logs which might be helpful. 

```
[ +367 ms] executing: /usr/bin/xcrun simctl install 93D69F2A-9579-48F5-978D-2DA683B15411 /Users/vivekmaskara/Documents/Projects/commons/build/ios/iphonesimulator/Runner.app
[+2553 ms] executing: /usr/bin/xcrun simctl launch 93D69F2A-9579-48F5-978D-2DA683B15411 com.maskaravivek.commons.share --enable-dart-profiling --enable-checked-mode --verify-entry-points
--observatory-port=0
[+13390 ms] com.maskaravivek.commons.share: -1

                     An error was encountered processing the command (domain=FBSOpenApplicationServiceErrorDomain, code=1):
                     The request to open "com.maskaravivek.commons.share" failed.
                     The request was denied by service delegate (SBMainWorkspace) for reason: NotFound ("Application "com.maskaravivek.commons.share" is unknown to FrontBoard").
                     Underlying error (domain=FBSOpenApplicationErrorDomain, code=4):
                        The operation couldn’t be completed. Application "com.maskaravivek.commons.share" is unknown to FrontBoard.
                        Application "com.maskaravivek.commons.share" is unknown to FrontBoard.
[   +3 ms] ProcessException: Process "/usr/bin/xcrun" exited abnormally:
           com.maskaravivek.commons.share: -1
           
           An error was encountered processing the command (domain=FBSOpenApplicationServiceErrorDomain, code=1):
           The request to open "com.maskaravivek.commons.share" failed.
           The request was denied by service delegate (SBMainWorkspace) for reason: NotFound ("Application "com.maskaravivek.commons.share" is unknown to FrontBoard").
           Underlying error (domain=FBSOpenApplicationErrorDomain, code=4):
                The operation couldn’t be completed. Application "com.maskaravivek.commons.share" is unknown to FrontBoard.
                Application "com.maskaravivek.commons.share" is unknown to FrontBoard.
             Command: /usr/bin/xcrun simctl launch 93D69F2A-9579-48F5-978D-2DA683B15411 com.maskaravivek.commons.share --enable-dart-profiling --enable-checked-mode --verify-entry-points
--observatory-port=0
[   +2 ms] Error launching application on iPhone Xʀ.
[   +2 ms] "flutter run" took 39,374ms.
[        ] "flutter run" took 39,374ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:24:3)
#1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:434:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:559:18)
#3      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#4      _rootRunUnary (dart:async/zone.dart:1132:38)
#5      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#6      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#8      Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#9      Future._complete (dart:async/future_impl.dart:473:7)
#10     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#11     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:28:18)
#12     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:294:13)
#13     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#14     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#15     _rootRunUnary (dart:async/zone.dart:1132:38)
#16     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#17     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#18     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#19     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#20     Future._complete (dart:async/future_impl.dart:473:7)
#21     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#22     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async-patch/async_patch.dart:33:20)
#23     _rootRun (dart:async/zone.dart:1124:13)
#24     _CustomZone.run (dart:async/zone.dart:1021:19)
#25     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#26     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#27     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#28     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:115:13)
#29     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:5)

```

**Comment by maskaravivek** [comment]
I was able to figure out the issue. Something to do with `Other linker flags`. Removed it and the build started working. :)

**Comment by EHBradford** [comment]
Question:  I have same issue.   Did you remove everything in the other linker flags?  I have around 100 items and I am hesitant to remove all 100 of them.  I would not know how to recreate them if I needed to.

**Comment by KasemJaffer** [comment]
> Question: I have same issue. Did you remove everything in the other linker flags? I have around 100 items and I am hesitant to remove all 100 of them. I would not know how to recreate them if I needed to.

Yes, you have to remove everything in other linker flags (ONLY FROM YOUR SHARE EXTENSION MODULE NOT YOUR HOST APP). Keep a backup if you revert this.
